[package]
name = "nb-field-names"
version = "0.1.0"
edition = "2021"
description = "generate class methods of returning field names of structs"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.39"
